import random

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3

NUM_OF_ROWS = 25
NUM_OF_COLS = 50
NUM_OF_MINES = 20

EMPTY = "_"
FLAG = "F"
MINE = "X"
SOLDIER = "S"

KEYS = ["up", "down", "left", "right"]

BC_DARK = (72, 72, 72)
BACKGROUND_COLOR = (00 ,33 ,00)
DISPLAY_SIZE = (500, 250)

GRASS_SIZE = (30, 10)
FLAG_SIZE = (40, 30)
SOLDIER_SIZE = (20, 40)

#GRASS_PLACMENT_X =  random.randrange(0, 470)
#GRASS_PLACMENT_Y = random.randrange(0, 240)
SOLDIER_PLACMENT_X = 0
SOLDIER_PLACMENT_Y = 0
FLAG_PLACMENT_X = 460
FLAG_PLACMENT_Y = 220


#GRASS_PLACMENT = (GRASS_PLACMENT_X, GRASS_PLACMENT_Y)
SOLDIER_PLACMENT = (SOLDIER_PLACMENT_X, SOLDIER_PLACMENT_Y)
FLAG_PLACMENT = (FLAG_PLACMENT_X, FLAG_PLACMENT_Y)

GRASS_LIST = []
for time in range(22):
    GRASS_PLACMENT_X = random.randrange(0, 470)
    GRASS_PLACMENT_Y = random.randrange(0, 240)
    GRASS_PLACMENT = (GRASS_PLACMENT_X, GRASS_PLACMENT_Y)
    GRASS_LIST.append(GRASS_PLACMENT)

TILE_SIZE = 10
STEP = 10

mines = []

FONT_NAME = "Calibri"
LOSE_MESSAGE = "You Lost!"
FONT_SIZE = int(0.1 * 500)
LOSE_COLOR = (54, 00, 20)
LOSE_LOCATION = \
    (0.2 * 500, 250 / 2 - (FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * 500, 250 / 2 - (FONT_SIZE / 2))
